### ISSUE TITLE
Comparison to the Amazon EC2 Plugin?

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/ec2-fleet-plugin#178]
I wonder what is the difference between this plugin and https://plugins.jenkins.io/ec2/ ?

I guess the main difference is this plugin work off of a spot fleet and/or auto-scaling group. 
The other plugin seems to manage scaling on it's own and starts ad-hoc EC2 instances. 

Am I missing anything else? 
What would be the practical considerations to choose this or the other plugin?

**Comment by lbly** [comment]
I don't seem to be able to create an init script for workers so that might be a consideration.

**Comment by imuqtadir** [comment]
Yes you are right. EC2 Fleet plugin supports ASG and Spot Fleet and brings all the benefits associated to it whereas EC2 Plugin uses RunInstance EC2 API which requires ad-hoc instances. In EC2 Fleet, the desired capacity of the fleet is calculated by the plugin based on the builds and other settings provided by the users and the fleet target capacity is adjusted based on it. I will keep this issue open to update README with the comparison of both the plugins so that it's helpful to others too.

**Comment by aw-was-here** [comment]
Maybe I'm just missing it, but it appears that ec2-fleet always requires at least one instance running. That's a huge economic incentive not to use it for queues that have long periods of zero traffic. (e.g., the weekend)
