### ISSUE TITLE
Make getRecurrencePeriod() return Configurable

### ISSUE THREAD

**Issue by alexelent** [jenkinsci/ec2-fleet-plugin#18]
When running a lot (20 for us) of unique Jenkins clusters with unique Spot Fleets we start running into RequestLimitExceeded error responses from Amazon. Configuring the timer to something less aggressive will help us work around this. The current constant of 10000ms is now hardcoded.

**Comment by terma** [comment]
Similar to #60

**Comment by terma** [comment]
@alexelent if you still interesting in a few, attached issue #60 has info about a possible fix, which you probably can try before release.

**Comment by terma** [comment]
@alexelent fix released under version [1.2.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.2.2). It doesn't change timeout in ```10sec``` as it create diff problems with stale data but significally reduce amount of calls to EC2 API because of batch.

I will close this issue, fleel free to reopen it if you have questions/problems.
