### ISSUE TITLE
EC2 Fleet won't scale up in No Delay Provision Strategy

### ISSUE THREAD

**Issue by curlytopps** [jenkinsci/ec2-fleet-plugin#260]
Our EC2 fleet is configured in Jenkins with no delay provision strategy so that it will spin up new nodes as the queue grows.
![JenkinsCloudConfig](https://user-images.githubusercontent.com/67361199/109804675-79ab3c00-7c5d-11eb-91b5-814f35540ae6.PNG)

However, the build queue is 7 in this case, and the node 

![BuildQueue](https://user-images.githubusercontent.com/67361199/109803862-8a0ee700-7c5c-11eb-83f3-e1d8deaf2423.PNG)

Jenkins logs show the currentDemand is 0 even though the build queue is already 7. Note that all of the jobs queued up may only be built in Slave2_EC2_BuildServer and the slaves in the EC2 fleet, so I assume the current Demand would be all 7 jobs?

![Jenkins logs](https://user-images.githubusercontent.com/67361199/109803868-8bd8aa80-7c5c-11eb-9df4-11e3c40f2f28.PNG)

**Comment by haugenj** [comment]
:wave: @curlytopps 

The `currentDemand` is 0 because it's calculated as the difference between `availableCapacity` and the job queue size. In this case, `availableCapacity` is 7 because `plannedCapacitySnapshot` is 7, meaning Jenkins has requested that 7 new executors come online. It still takes a bit of time for the EC2 instances to spin up and for the Jenkins agent to get initialized at that point 

a couple questions: 
- Are the nodes eventually getting provisioned?
- Do you see any events in CloudTrail related to the ASG or Fleet you're using? 
- Are you able to reproduce this by following any specific steps? 
- Does this happen all the time or just randomly?

**Comment by curlytopps** [comment]
So the setup is that each node in the fleet can only have one executor. If Jenkins has requested that 7 new executors come online, and Slave2_EC2_BuildServer contributes only 1 executor, then Jenkins should have sent modify request of 5 (max) to the Spot request resource? When I submitted the issue, the Spot Fleet resource in AWS has not received a modify request, the target and desired capacity was 0.

> Are the nodes eventually getting provisioned?
The nodes only got provisioned after I restarted jenkins master. 
Upon restarting jenkins, it suddenly set its target to 5 nodes, and the fleet upscaled to 5.

> Do you see any events in CloudTrail related to the ASG or Fleet you're using?

Here's the cloud trail screenshot for the EC2 Spot Fleet request. I annotated it with the target capacity requested (in red) for each request.
![image](https://user-images.githubusercontent.com/67361199/109841904-7e371b00-7c84-11eb-83c2-45e872b51416.png)

> Are you able to reproduce this by following any specific steps?
I'm not sure how to reproduce it. Restarting jenkins seems to fix it when it gets stuck.

> Does this happen all the time or just randomly?
> 


The EC2 fleet has actually been operational for weeks already and is able to scale in and out. It seems to get stuck randomly

**Comment by haugenj** [comment]
Hmm if the limit is 5 but `plannedCapacitySnapshot` is 7 then I would guess the state of the plugin and Jenkins got messed up somehow. The only way we were able to reproduce errors like this before is when the plugin configuration was saved while there were pending jobs in the queue. If you changed any of the plugin settings somewhat recently that could be the cause, otherwise I'm not so sure.

Which version of the plugin and Jenkins are you using?

**Comment by curlytopps** [comment]
2.3.2

**Comment by haugenj** [comment]
@curlytopps have you noticed this bug occur after leaving the plugin configuration alone for a while? Or does it tend to appear soon after you make modifications to the plugin?

**Comment by curlytopps** [comment]
I had not made any changes to the plugin 48 hours before the issue occurred.  I am also the only admin who has perms to the Configure Clouds page.

**Comment by prakashemeascm** [comment]
Hi Team, 

We are also facing the same exact issue (EC2 Fleet wnot scale up in "No Delay Provision Strategy" option is enabled) and we have installed the ec2-fleet-plugin:2.0.2 version.

Once Instance is having 4 executors if the instance is fully occupied even though when the job are in queue the instance are not getting provision.

It was working fine, but since last week we are facing issue.

We have seen the below log in jenkins, 
`2021-04-19 12:42:24.968+0000 [id=29]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: currentDemand 27 availableCapacity 12 (availableExecutors 12 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)`

Here below is the config for fleet plugin:
![image](https://user-images.githubusercontent.com/82818220/115239071-fe81e480-a13b-11eb-8a2d-5d5d608dfa36.png)

**Comment by szy54** [comment]
I am also facing this issue at $job, it's at least a second time. It seems that there's no workaround when it occurs since I don't consider jenkins restart as a workaround, - at least if we talk about serious company-wide used jenkins controller, you can't afford a restart in the middle of the day :(
It definitely emerges in our case after making change to plugin configuration and for sure there were jobs queued when the configuration was applied/saved. 
Example use case:
> you run jenkins with "hybrid" nodes - some part of them are physical machines that you own in your infra and the other part are spot fleets managed by the plugin. They offer different labels
> there's some incident that disables your physical machines so you want to spin up a new AWS spot fleet to handle the work (recognized by different labels) that was carried by the physical nodes
> you apply a configuration on the fly and it may get even worse

It's a pity that a plugin is currently unable to handle such use case. Do you plan to deal with this limitation somehow and maybe need some additional info/logs about this?
