### ISSUE TITLE
AMI refresh support

### ISSUE THREAD

**Issue by michalszelagsonos** [jenkinsci/ec2-fleet-plugin#345]
**Is your feature request related to a problem? Please describe.**
I am uncertain how the plugin will react to this scenario, so posting here to solicit feedback and go from there.  ASGs support an AMI refresh feature and I am curious to learn how the plugin behaves in such a scenario.  For example, when a new AMI version becomes available, the launch template can be updated to reference it, and the ASG can perform a fleet refresh where nodes are rolled, one or more at a time, while maintaining minimum capacity in the group.  This is super useful for rolling out AMI upgrades while maintaining some capacity to run the workloads.  I am curious what happens when the ASG starts to refresh instances.  Does the plugin deal with this scenario gracefully where nodes go offline and when they come up, they reattach themselves to the controller and can start accepting workloads?  Or is the outcome different in such a case?  

ASG refresh doc: https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/

**Describe the solution you'd like**
When a group refresh occurs, I would like the nodes to come back gracefully, reattach themselves to the controller, come online and start running workloads.

**Describe alternatives you've considered**
Auto refresh is an important aspect in my environment so if the plugin is unable to deal with such scenarios, I may have to consider another option which includes not using the plugin and instead roll my own fleet management solution, like the swarm plugin.

**Additional context**
My environment runs non-spot instances where the nodes may persist for quite a while so AMI refresh functionality is critical to achieving reliable and consistent operations.

**Comment by wosiu** [comment]
[Disclaimer I'm not a maintainer, but..] AFAIK - no, there is no such mechanism on the plugin side. In fact ASG should not control any operations which might cause removing/restarting an agent, because it might be in the middle of the job.

The way we handle that, is to set both in the plugin's configuration:
1) `Max Idle Minutes Before Scaledown`
2) `Maximum Total Uses`

So it's kinda heuristic, but it works in our case, because machines are eventually rotated because of one of those 2 configurations above (pretty quickly depending on the numbers you set). If you need something more prompt, I guess you can implement a script to be run in jenkins console (or scriptler), that marks agents offline, so that they finish their current tasks, but do not accept more work.

And there is a similar information in the [faq](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/docs/FAQ.md#faq):
> Q: Why does the plugin keep enabling scale-in protection on my ASG?
> A: The plugin handles termination of instances manually based on idle period settings. Without scale-in protection enabled, instances could be terminated unexpectedly by external conditions and running jobs could be interrupted.

Having all that said, it would be very hard to make the native ASG feature for rolling new AMI to work with the plugin in my opinion. The control plane here must be a jenkins. I can imagine jenkins asking aws periodically if there is a new ami configured for a given ASG, and then perfoming machines rotation, but it won't use the builtin AWS feature.

**Comment by gnydick** [comment]
I second the request to support the swarm plugin. It just makes things so much easier if the nodes can connect themselves. There are no credentials or remote management to deal with from the Jenkins controller side. I agree, I don't want my AWS ASG handling scaling. I just would like the ec2-fleet plugin to be able to manage the fleet and be able to identify the swarm created nodes.

**Comment by michalszelagsonos** [comment]
To clarify my request, I do think that having Jenkins be in control of the scaling makes most sense.  It understands the load, it knows whether a node is running a workload, it is in the best position to scale in and out when needed.  Here is what is driving my questions, which is probably not a typical environment.  I have a fleet of MacOS AWS nodes that Jenkins is managing as nodes.  I'd like this pool to have some elasticity and I want to manage the nodes using immutable infrastructure (AMI).  Note, due to Apple's licensing terms, a node has to remain up for at least 24 hours before it can be shut down.  So, what I'd love to see is as follows:
- the plugin scales in and out based on load using existing policy.  Since Jenkins has affinity for using nodes that were last used for a job, I believe scale-in based on idle time may be enough to manage this, although another criteria based on age would be wonderful here.  If I could scale in after min 24hours and idle time, that would be very nice.
- AMI refresh is a critical feature when it comes to managing the infrastructure, especially when the lifecycle of a node has some longevity to it.  I think it would be great to consider some kind of feature in the plugin to facilitate this.  Based on the diagram in the docs, the plugin already knows how to discover new nodes, I am guessing that it is using ASG API to scale out, initiating an auto refresh is an ASG API call, it doesn't "seem" that crazy to think a controller initiated refresh is possible.  Note, I didn't go through the plugin code so I am making assumptions based on current capabilities and AWS API.
