### ISSUE TITLE
Is this plugin still actively maintained?

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [jenkinsci/ec2-fleet-plugin#366]
_Unfortunately, I can't open a discussion. Please excuse me if I'm not following the intended process._ 

I'm stumbled upon this plugin since it sounds very interesting and seems to fit my needs.

The lastest release is 9 months old and there seem to be some (serious) issues which got no response yet:
* #363 
* #364 
* #361 
* #360 
* #359
* #358
* #322 

There is also not activity in [gitter](https://app.gitter.im/#/room/#ec2-fleet-plugin_community:gitter.im) since last year.

**So I would kindly like to ask if this plugin is still under active maintenance or is it up for adoption?**

**Comment by mwos-sl** [comment]
I'd add this one to blocker list: https://github.com/jenkinsci/ec2-fleet-plugin/issues/322
After several tries and experiments with configuration, we had to drop using this plugin because it made our jenkins unusable 😭 I don't think the plugin is maintained. The worst part is that AWS officially says it's possible to use spot workers on jenkins using this plugin: https://aws.amazon.com/blogs/compute/cost-optimize-your-jenkins-ci-cd-pipelines-using-ec2-spot-instances/, but without this plugin working it is actually not possible 😞

**Comment by pdk27** [comment]
Hello, 
Thanks for raising the question! Unfortunately, the developers who maintained this plugin moved on last year and we have been operating on reduced bandwidth since. We are currently working on rebuilding the context and addressing open issues.

**Comment by pdk27** [comment]
Hello, 
We are currently working on a number of open issues to bring this plugin to a well-maintained state. Thanks to the community's helpful comments on issues. We are getting there - 2 new releases were published recently and more to follow. 🚀
