### ISSUE TITLE
Maximum Total Uses cannot be changed and it always appears as -1

### ISSUE THREAD

**Issue by benipeled** [jenkinsci/ec2-fleet-plugin#397]
## Issue Details

**Describe the bug**
When creating a new fleet or editing an existing one, whatever you set on the `Maximum Total Uses` option, will be changed to `-1`. I'm not sure if it's UI bug only

**To Reproduce**
1. Create a new `Amazon EC2 Fleet` cloud
2. Set the `Maximum Total Uses` to 1

Result: `Maximum Total Uses` set to `-1`
Expected result: `Maximum Total Uses` set to `1`

## Environment Details

**Plugin Version?**
2.7.1

**Jenkins Version?**
2.418

**Spot Fleet or ASG?**
Spot Fleet

**Label based fleet?**
No

**Linux or Windows?**
Linux

**Comment by vineeth-bandi** [comment]
@benipeled 
It seems like this bug is mostly visual. The problem appears to be that every time the Jenkins Cloud Configuration page is loaded, the value is set as the default value of `-1` in the UI. This can cause a problem if you change a setting in any Cloud but don't change the value of `Maximum Total Uses` to the intended value. I will look into a fix.
