### ISSUE TITLE
Scale-in Protection always enable

### ISSUE THREAD

**Issue by nolimitzjr** [jenkinsci/ec2-fleet-plugin#419]
Why is the scale-in protection always enabled after creating a new instance? , Even i do uncheck in ASG, it will rollback the config to checked. There is any way to make it always disabled?

**Comment by pdk27** [comment]
Hello, 
The plugin handles termination of instances manually based on configuration and for the [following scenarios](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2AgentTerminationReason.java). Without scale-in protection enabled, instances could be terminated unexpectedly by external conditions and running jobs could be interrupted.
Due to this reason, the plugin will enable it even if the feature disabled. 

Feel free to re-open with a description of your use case if you have more to add. 
Also, there are [FAQs](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/docs/FAQ.md#faq) here that might help.

**Comment by nolimitzjr** [comment]
Thanks for reply, and how to terminate the instance if we already set idle
to scale down?

Pada Jum, 3 Nov 2023 17.17, Prathibha Datta Kumar ***@***.***>
menulis:

**Comment by pdk27** [comment]
@nolimitzjr Can you share the configuration you are using? 
Are you saying your instances are not terminated even if they are idle and you have set an appropriate `Max Idle Minutes Before Scaledown`?

**Comment by nolimitzjr** [comment]
It was terminated but in Instance Management the instance that was
terminated still stuck in there

Pada Jum, 3 Nov 2023 18.50, Prathibha Datta Kumar ***@***.***>
menulis:

**Comment by pawel-t** [comment]
I've missed this one and opened new issue: [](https://github.com/jenkinsci/ec2-fleet-plugin/issues/432 )

@pdk27 In my case they are not removed as requested. It take much longer for them to shutdown and eventually they scale down but it's not within time that was set via max idle. I often see few messages from AWS to related problem.
